### ISSUE TITLE
hi。

### ISSUE THREAD

**Issue by yuexunshi** [mengdd/PreferencesProvider#9]
UncaughtException detected: java.lang.IllegalArgumentException: Unknown URL null/preferences
                                                     at android.content.ContentResolver.insert(ContentResolver.java:1276)
                                                     at com.vpgame.eric.utils.preferencesprovider.provider.base.AbstractContentValues.insert(AbstractContentValues.java:34)
                                                     at com.vpgame.eric.utils.preferencesprovider.provider.PreferencesHelper.insert(PreferencesHelper.java:40)
                                                     at com.vpgame.eric.utils.preferencesprovider.provider.PreferencesHelper.insert(PreferencesHelper.java:31)
                                                     at com.vpgame.eric.utils.preferencesprovider.provider.PreferencesStorageModule.put(PreferencesStorageModule.java:39)
                                                     at com.vpgame.eric.utils.preferencesprovider.provider.base.PSUtils.put(PSUtils.java:27)
                                                     at com.vpgame.eric.ui.activity.mine.sign.signIn.MySignInFragment.setListener(MySignInFragment.java:165)
                                                     at com.vpgame.eric.ui.activity.mine.sign.signIn.MySignInFragment.initViews(MySignInFragment.java:147)
                                                     at com.vpgame.eric.ui.fragment.base.BaseFragment.onCreateView(BaseFragment.java:71)
                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                     at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
                                                     at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                     at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                     at android.view.View.measure(View.java:21046)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                     at android.view.View.measure(View.java:21046)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                     at android.view.View.measure(View.java:21046)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                     at android.view.View.measure(View.java:21046)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                     at android.view.View.measure(View.java:21046)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                     at android.view.View.measure(View.java:21046)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:785)
                                                     at android.view.View.measure(View.java:21046)
                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2555)
                                                 	at andro

**Comment by joychine** [comment]
最后没解决这个bug么，我也遇到了啊，是在web进程中查询

**Comment by yuexunshi** [comment]
> 最后没解决这个bug么，我也遇到了啊，是在web进程中查询

解决了，忘记了。。。
